# Data Accessing
In this step, the data is to be understood more deeply. Before implementing methods to clean it, you will definitely need to have a better idea about what the data is about.

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

In [ ]:
matches=pd.read_csv(r"C:\Users\Jakho\Downloads\archive\matches.csv")
matches

In [ ]:
print(matches.columns.tolist())
deliveries=pd.read_csv(r"C:\Users\Jakho\Downloads\archive\deliveries.csv")

In [69]:
matches[['team1','team2','toss_winner','winner']]=matches[['team1','team2','toss_winner','winner']].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru','Kings XI Punjab':'Punjab Kings','Delhi Daredevils':'Delhi Capitals','Rising Pune Supergiants':'Rising Pune Supergiant'})

In [72]:
with pd.ExcelWriter("ipl_files.xlsx") as writer:
    matches.to_excel(writer, sheet_name='matches',index=False)
    deliveries.to_excel(writer, sheet_name='deliveries',index=False)

In [41]:
deliveries.info()

<class 'pandas.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  str
 3   bowling_team      260920 non-null  str
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  str
 7   bowler            260920 non-null  str
 8   non_striker       260920 non-null  str
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   str
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   str
 15  dismissal_kind    12950 non-null   str
 16  fielder           9354 non-null    str
dtypes: int64(8), str(9)
memory usage: 33.8 MB

# Types of Unclean Data
There are 2 kinds of unclean data:  

**Dirty Data** (Data with Quality issues): Dirty data, also known as low quality data. Low quality data has content issues.  
    - Duplicated data  
    - Missing Data  
    - Corrupt Data  
    - Inaccurate Data  

**Messy Data** (Data with tidiness issues): Messy data, also known as untidy data. Untidy data has structural issues.Tidy data has the following properties:  
    - Each variable forms a column  
    - Each observation forms a row  
    - Each observational unit forms a table

# Types of Assessment
There are 2 types of assessment styles  
**Manual** - Looking through the data manually in google sheets  
**Programmatic** - By using pandas functions such as info(), describe() or sample()  
Steps in Assessment:  
There are 2 steps involved in Assessment  
    - Discover  
    - Document

# Automatic Assessment
    - head and tail
    - sample
    - info
    - isnull
    - duplicated
    - describe

# 1.Summary 
(write summery of the dataset)  
This is the data of ipl matches since 2007/08 season to 2024 season. It contains all data from ball to ball delivery to overall match record. It has two datasheet:  
- one is **Deliveries** to record ball to ball delivery, which bowler was bowling to which batsman and what happened on that ball and many more things.   
- The other datasheet is **Matches**, it record overall result of the match, which teams are playing at which venue etc.

# 2.MATCHES TABLE
(Add column description off all tables)  
-**id**- it is the match id  
-**season** - it is the ipl season  
-**city**- the city in which game is being played  
-**match_type** -it gives at what stage the game is being played(lleague stage, semifinal, final)  
-**player_of the match** - shows the player who played best in that game  
-**venue** - venue at which game is being played  
-**team_1**- team 1 playing the match(usually the host team)  
-**team_2** - team 2 playing the match  
-**toss_winner** - team that won the toss  
-**toss_decision** - decision to bat or field decided by the toss winning team captain  
-**winner** - winner of the match  
-**result** - whether the team won by wickets or runs. null for tied matches   
-**result_margin**- margin by which the team won the match  
-**target_runs** - runs that team batting second had to chase  
-**target_overs** - overs within which the team batting second had to chase the targeted runs. this is specifically used in D/L method situations (rain-affected matches) where the full 20 overs aren't possible. In a normal match it will just be 20.   
-**super_over** - whether the match had gone to superover or not, contains y/n  
-**method** - whether d/l was used or not. usually null for normal matches  
-**umpire1** - 1st on field umpire  
-**umpire_2** - 2nd on field umpire

# 3.additional Info
(Add any additional you collected from somewhere)

# 4.Issues in both table 
- **Messy Data**  
  - **Table - 'Matches'**  
    - In player of the match full name is not mentioned. Same with umpires name.  
    - Due to change in teams name same team is mentioned with 2 different names.  
  - **Table - 'Deliveries'**  
    - In player of the match full name is not mentioned and some players full name is mentioned. Same with umpires name.   
    - So when there ia a wide or no ball it is counted as a ball therefore total ball in that over goes over 6, it it diff to get total over bowled exact to the ball

- **Dirty Data**  
  - **Table - 'Matches'**  
    - In some matches the city is not mentioned especially in 2019/20 season  
    - In cell E321 "Elimination final" is mentioned instead of "Eliminator"  
  - **Table - 'Deliveries'**  
    - Nothing

In [28]:
deliveries.groupby(['match_id','inning','batting_team'])[['total_runs','is_wicket']].sum()

                                             total_runs  is_wicket
match_id inning batting_team
335982   1      Kolkata Knight Riders               222          3
         2      Royal Challengers Bangalore          82         10
335983   1      Chennai Super Kings                 240          5
         2      Kings XI Punjab                     207          4
335984   1      Rajasthan Royals                    129          8
...                                                 ...        ...
1426310  2      Rajasthan Royals                    174          6
1426311  1      Sunrisers Hyderabad                 175          9
         2      Rajasthan Royals                    139          7
1426312  1      Sunrisers Hyderabad                 113         10
         2      Kolkata Knight Riders               114          2

[2217 rows x 2 columns]

In [ ]:
deliveries.groupby(['match_id','inning','batting_team']).agg({'total_runs':'sum','is_wicket':'sum','over':'max','ball':'max'})

                                             total_runs  is_wicket  over  ball
match_id inning batting_team
335982   1      Kolkata Knight Riders               222          3    19     7
         2      Royal Challengers Bangalore          82         10    15     8
335983   1      Chennai Super Kings                 240          5    19     8
         2      Kings XI Punjab                     207          4    19     8
335984   1      Rajasthan Royals                    129          8    19     7
...                                                 ...        ...   ...   ...
1426310  2      Rajasthan Royals                    174          6    18     8
1426311  1      Sunrisers Hyderabad                 175          9    19     8
         2      Rajasthan Royals                    139          7    19     7
1426312  1      Sunrisers Hyderabad                 113         10    18     9
         2      Kolkata Knight Riders               114          2    10     8

[2217 rows x 4 columns]

In [52]:
print(deliveries.groupby(['batter'])['batsman_runs'].sum().sort_values(ascending=False).reset_index().head(10))

           batter  batsman_runs
0         V Kohli          8014
1        S Dhawan          6769
2       RG Sharma          6630
3       DA Warner          6567
4        SK Raina          5536
5        MS Dhoni          5243
6  AB de Villiers          5181
7        CH Gayle          4997
8      RV Uthappa          4954
9      KD Karthik          4843

In [ ]:
top_batsman=deliveries.groupby(['batter'])['batsman_runs'].sum().sort_values(ascending=False).head(10).reset_index()
top_batsman.columns=['Batsman','Runs Scored']
top_batsman.index.name='Sr No.'
top_batsman.index=top_batsman.index+1
top_batsman

               Batsman  Runs Scored
Sr No.
1              V Kohli         8014
2             S Dhawan         6769
3            RG Sharma         6630
4            DA Warner         6567
5             SK Raina         5536
6             MS Dhoni         5243
7       AB de Villiers         5181
8             CH Gayle         4997
9           RV Uthappa         4954
10          KD Karthik         4843

In [78]:
# Count wins per team
total_matches = pd.concat([matches['team1'], matches['team2']]).value_counts()
wins = matches['winner'].value_counts()
win_rate_df = (wins / total_matches * 100).sort_values(ascending=False).reset_index()
win_rate_df.columns = ['Team', 'win_rate']
win_rate_df.index.name ='Sr No.'
win_rate_df.index=win_rate_df.index+1
print(win_rate_df)

                               Team   win_rate
Sr No.
1                    Gujarat Titans  62.222222
2               Chennai Super Kings  57.983193
3                    Mumbai Indians  55.172414
4              Lucknow Super Giants  54.545455
5             Kolkata Knight Riders  52.191235
6                  Rajasthan Royals  50.678733
7            Rising Pune Supergiant  50.000000
8               Sunrisers Hyderabad  48.351648
9       Royal Challengers Bengaluru  48.235294
10                   Delhi Capitals  45.634921
11                     Punjab Kings  45.528455
12                    Gujarat Lions  43.333333
13             Kochi Tuskers Kerala  42.857143
14                  Deccan Chargers  38.666667
15                    Pune Warriors  26.086957

In [73]:
pd.concat([matches['team1'], matches['team2']]).value_counts()

Mumbai Indians                 261
Royal Challengers Bengaluru    255
Delhi Capitals                 252
Kolkata Knight Riders          251
Punjab Kings                   246
Chennai Super Kings            238
Rajasthan Royals               221
Sunrisers Hyderabad            182
Deccan Chargers                 75
Pune Warriors                   46
Gujarat Titans                  45
Lucknow Super Giants            44
Gujarat Lions                   30
Rising Pune Supergiant          30
Kochi Tuskers Kerala            14
Name: count, dtype: int64

In [80]:
fig = plt.figure(figsize=(16, 12))
fig.suptitle('IPL Dashboard (2008–2020)', fontsize=18, fontweight='bold', y=0.98)
gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.45, wspace=0.35)

In [82]:
ax1 = fig.add_subplot(gs[0, :])  # full top row
colors = plt.cm.YlOrRd(np.linspace(0.4, 0.9, 10))
bars = ax1.barh(top_batsman['Batsman'], top_batsman['Runs Scored'], color=colors)
ax1.set_xlabel('Total Runs')
ax1.set_title('Top 10 IPL Run Scorers (all seasons)')
ax1.invert_yaxis()
for bar, val in zip(bars, top_batsman['Runs Scored']):
    ax1.text(bar.get_width() + 50, bar.get_y() + bar.get_height()/2,
             f'{int(val):,}', va='center', fontsize=9)

In [83]:
ax2 = fig.add_subplot(gs[1, 0])
win_rate_df_top = win_rate_df.head(8)
ax2.barh(win_rate_df_top['Team'], win_rate_df_top['win_rate'],
         color='steelblue')
ax2.set_xlabel('Win Rate (%)')
ax2.set_title('Team Win Rates')
ax2.invert_yaxis()

In [84]:
plt.savefig('ipl_dashboard.png', dpi=150, bbox_inches='tight')
plt.show()
print("Dashboard saved!")

Dashboard saved!